<template>
  <div class="bg-gray-100 flex justify-center items-start font-sans text-gray-800">
    <div class="page bg-white w-full max-w-3xl shadow-lg rounded-lg p-8">
      <!-- Header -->
      <header class="flex justify-between items-start mb-6 border-b pb-4">
        <div>
            <div class="flex items-center">
                <Logo size="w-6 h-6" color="text-primary-600" />
                <p class="ml-2 text-2xl font-extrabold font-inter text-primary-600">LeaseDirector</p>
            </div>
          <p class="text-sm text-gray-500">Property Management for Small Landlords</p>
          <p class="text-sm text-gray-500">www.leasedirector.com</p>
        </div>
        <div class="text-right">
          <h2 class="text-xl font-semibold text-gray-800">PROPERTY INVOICE</h2>
          <p class="text-sm text-gray-500 mt-1">
            Invoice #: <span class="font-medium text-gray-700">{{ invoiceNumber }}</span>
          </p>
          <p class="text-sm text-gray-500">
            Date: <span class="font-medium text-gray-700">{{ invoiceDate }}</span>
          </p>
        </div>
      </header>

      <!-- Tenant & Property Info -->
      <section class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        <div>
          <h3 class="text-sm font-semibold text-gray-700 mb-1">Bill To (Tenant)</h3>
          <p class="text-sm">{{ tenant.name }}</p>
          <p class="text-sm">{{ tenant.address }}</p>
          <p class="text-sm">{{ tenant.city }}</p>
          <p class="text-sm">Email: {{ tenant.email }}</p>
        </div>

        <div class="md:text-right">
          <h3 class="text-sm font-semibold text-gray-700 mb-1">Property Details</h3>
          <p class="text-sm">Property: {{ property.name }}</p>
          <p class="text-sm">Unit: {{ property.unit }}</p>
          <p class="text-sm">Rent Period: {{ property.period }}</p>
          <p class="text-sm">Due Date: {{ property.dueDate }}</p>
        </div>
      </section>

      <div class="min-h-[45%]">
      <!-- Table -->
        <table class="w-full border-collapse mb-6">
            <thead>
            <tr class="bg-gray-50 border-b">
                <th class="text-left text-xs font-semibold uppercase py-2 px-3 text-gray-600">#</th>
                <th class="text-left text-xs font-semibold uppercase py-2 px-3 text-gray-600">Description</th>
                <th class="text-center text-xs font-semibold uppercase py-2 px-3 text-gray-600">Qty</th>
                <th class="text-right text-xs font-semibold uppercase py-2 px-3 text-gray-600">Rate (USD)</th>
                <th class="text-right text-xs font-semibold uppercase py-2 px-3 text-gray-600">Amount (USD)</th>
            </tr>
            </thead>
            <tbody>
            <tr
                v-for="(item, i) in items"
                :key="i"
                class="border-b"
            >
                <td class="py-2 px-3 text-sm text-gray-700">{{ i + 1 }}</td>
                <td class="py-2 px-3 text-sm text-gray-700">{{ item.description }}</td>
                <td class="py-2 px-3 text-center text-sm text-gray-700">{{ item.qty }}</td>
                <td class="py-2 px-3 text-right text-sm text-gray-700">${{ item.rate.toFixed(2) }}</td>
                <td class="py-2 px-3 text-right text-sm text-gray-700">${{ (item.qty * item.rate).toFixed(2) }}</td>
            </tr>
            </tbody>
        </table>

        <!-- Totals -->
        <div class="flex justify-end">
            <div class="w-full max-w-sm">
            <div class="flex justify-between py-1 border-b text-sm">
                <span class="text-gray-600">Subtotal</span>
                <span class="font-medium">${{ subtotal.toFixed(2) }}</span>
            </div>
            <div class="flex justify-between py-1 border-b text-sm">
                <span class="text-gray-600">Tax ({{ taxRate }}%)</span>
                <span class="font-medium">${{ taxAmount.toFixed(2) }}</span>
            </div>
            <div class="flex justify-between py-2 border-t text-base font-semibold">
                <span>Total Due</span>
                <span>${{ totalDue.toFixed(2) }}</span>
            </div>
            </div>
        </div>
      </div>

      <!-- Payment Info -->
      <div class="mt-8">
        <h3 class="text-sm font-semibold text-gray-700 mb-1">Payment Details</h3>
        <p class="text-sm">Pay to: {{ payment.bankName }}</p>
        <p class="text-sm">Bank: {{ payment.bank }}</p>
        <p class="text-sm">Account Number: {{ payment.account }}</p>
        <p class="text-sm">SWIFT Code: {{ payment.swift }}</p>
      </div>

      <!-- Footer -->
      <footer class="mt-10 border-t pt-4 text-center">
        <p class="text-xs text-gray-500">
          Generated by
          <a href="https://www.leasedirector.com" class="text-primary-600 underline" target="_blank">
            LeaseDirector.com
          </a>
          — Property Management for Small Landlords
        </p>
        <p class="text-xs text-gray-400 mt-1">
          This is a computer-generated document. No signature required.
        </p>
      </footer>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'

interface Tenant {
  name: string
  address: string
  city: string
  email: string
}

interface Property {
  name: string
  unit: string
  period: string
  dueDate: string
}

interface Item {
  description: string
  qty: number
  rate: number
}

interface Payment {
  bankName: string
  bank: string
  account: string
  swift: string
}

const props = defineProps<{
  invoiceNumber: string
  invoiceDate: string
  tenant: Tenant
  property: Property
  items: Item[]
  taxRate: number
  payment: Payment
}>()

// computed totals
const subtotal = computed(() =>
  props.items.reduce((sum, item) => sum + item.qty * item.rate, 0)
)
const taxAmount = computed(() => (subtotal.value * props.taxRate) / 100)
const totalDue = computed(() => subtotal.value + taxAmount.value)

</script>

<style>
@media print {
  body {
    background: #fff !important;
    padding: 0 !important;
  }
  .no-print {
    display: none !important;
  }
  .page {
    box-shadow: none !important;
    margin: 0 !important;
  }
}
</style>
